# https://codingpointer.com/ansible/download-shell-scripts-from-remote
---
- hosts: all
  become: yes
  tasks:
    - name: "creating directory"
      file:
        state: directory
        path: /tmp/ansible/test_shell
        mode: 0750
