# https://codingpointer.com/ansible/download-shell-scripts-from-remote
---
- hosts: all
  become: yes
  tasks:
    - name: "creating directory"
      file:
        state: directory
        path: /tmp/ansible/test_shell
        mode: 0755
    - name: download get_host_name.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/cutefly/ansible-semaphore/main/scripts/get_host_name.sh
        dest: /tmp/ansible/test_shell/get_host_name.sh
        mode: '0440'
    - name: run shell file
      shell: ". /tmp/ansible/test_shell/get_host_name.sh"
#    - name: get host name
#      shell: "echo $(hostname -f) > /tmp/ansible/test_shell/shell_file"
    - name: read file content
      command: "cat /tmp/ansible/test_shell/shell_file"
      register: out
    - name: Print the msg
      debug:
        msg: "{{ out.stdout }}"
