# https://sujitpatel.in/article/how-to-install-nginx-using-ansible-playbook/
---
- hosts: ubuntu
  become: yes
  tasks:
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: uninstall nginx
      apt: name=nginx state=absent autoremove=yes
