---
  
- hosts: ubuntu
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: true

  tasks:
    - name: Update and upgrade yum packages
      yum:
        update_cache: yes
        state: latest
